//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotAndMaze.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotAndMaze.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to == End Game ==.
        /// </summary>
        internal static string EndGame {
            get {
                return ResourceManager.GetString("EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [x] - Exit game.
        /// </summary>
        internal static string ExitGame {
            get {
                return ResourceManager.GetString("ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [s] - Move back.
        /// </summary>
        internal static string MoveBack {
            get {
                return ResourceManager.GetString("MoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [z] - Move DownLeft.
        /// </summary>
        internal static string MoveDownLeft {
            get {
                return ResourceManager.GetString("MoveDownLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [c] - Move DownRight.
        /// </summary>
        internal static string MoveDownRight {
            get {
                return ResourceManager.GetString("MoveDownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [w] - Move forward.
        /// </summary>
        internal static string MoveForward {
            get {
                return ResourceManager.GetString("MoveForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a] - Move left.
        /// </summary>
        internal static string MoveLeft {
            get {
                return ResourceManager.GetString("MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [d] - Move righ.
        /// </summary>
        internal static string MoveRight {
            get {
                return ResourceManager.GetString("MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [q] - Move UpLeft.
        /// </summary>
        internal static string MoveUpLeft {
            get {
                return ResourceManager.GetString("MoveUpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [e] - Move UpRight.
        /// </summary>
        internal static string MoveUpRight {
            get {
                return ResourceManager.GetString("MoveUpRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Select a movement ----.
        /// </summary>
        internal static string SelectMovement {
            get {
                return ResourceManager.GetString("SelectMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===============.
        /// </summary>
        internal static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to == Start Game ==.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown option.
        /// </summary>
        internal static string UnknownOption {
            get {
                return ResourceManager.GetString("UnknownOption", resourceCulture);
            }
        }
    }
}
